### ISSUE TITLE
Add match & revise syntax transformations

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_transforms#101]
Suggested syntax / configuration.

Suppose a transformation has a `stage_cfg` that normally takes some arguments. As all `stage_cfg`s are dictionaries, we can do the following:

If (for transformations that support match & revise), the `stage_cfg` has a `_match_and_revise` key, then:
  1. All other `stage_cfg` keys are assumed to be global default values.
  2. An error is thrown if each element of the `_match_and_revise` is not a list of dictionaries with each having at least a `_matcher` key which points to a valid `match_configuration` object (validity criteria yet to be determined).
  3. The transformation will be run for each element of the `_match_and_revise` list filtered to only those measurements that match the `_matcher` key value, using all other keyword arguments of the list element as the `stage_cfg` arguments for that revision run, defaulting to global arguments.

**Comment by mmcdermott** [comment]
This will be much easier (or maybe only feasible if) we solve #102 first.

**Comment by mmcdermott** [comment]
@prenc other than applying the splitting logic to only blood pressure codes, are there other codes for which you apply match-revise logic? Or is this not acutely needed outside of #58 ?

**Comment by prenc** [comment]
> @prenc other than applying the splitting logic to only blood pressure codes, are there other codes for which you apply match-revise logic? Or is this not acutely needed outside of #58 ?

@mmcdermott I apply match-revise logic in the most of my transformations, because I take a subset and somehow manipulate it. It's an atomic operation for me. Not sure if the scopes of what we consider match&revise are equal.

**Comment by mmcdermott** [comment]
thanks, this is very helpful. Here are a breakdown of where I see you using this capability so far:
  1. [In re-ordering transforms](https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L12C1-L15C1), which can be handled in this library via #47 without match & revise.
  2. [In code-specific timestamp modification](https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L17C1-L24C1), which I only observe in settings that should be handled in the pre-MEDS step in this library (in particular,  #103)
  3. [Static code aggregation / re-mapping](https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L27C1-L30C1). We should introduce a new issue for this in this repo, but it doesn't need match & revise I don't think given that the codes to re-map will dictate directly which codes they apply to. Does that sound right?
    - Another example: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L203C1-L215C1 Note this would require code remapping to support external file lookup.
    - https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L216C1-L244C10 is similar. This one could actually use the `description` column in the `metadata/codes.parquet`, though, maybe?]
    - There are similar examples for procedure codes.
  5. [An extraction of categorical values into the code from the `text_value`](https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L76C1-L86C100). This, if truly necessary and not something we should just adjust in the MIMIC-IV event configs file, **would** require match and revise in this library.
  6. Some more, non-BP examples of `split_measurements.py`, I think (https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L90C1-L113C1). This could be handled by `split_measurements` if we gave it a custom built-in match and revise.
  7. In another numerical conversion one that actually may also motivate #57 to be re-promoted: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L388C3-L399C10
  8. In some code string operations matching, which may motivate a different transform function for code string manipulation, and would potentially be a good candidate for this: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L417C1-L426C10
  9. An application of the existing `filter_measurements.py` transform but only on a certain prefix, so that would also need a general `match_and_revise` framework: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L429C2-L437C26


I'm not sure about the below uses:
  1. https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L114C4-L161C10
  2. https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L331C1-L371C1 -- this we should likely think about other solutions for if possible. Or this should be interpreted as joining in external data or features or some sort of transform like that.

Does my above summary seem right @prenc?
