### ISSUE TITLE
Static DataFrame Missing Rows for Patients Without Static Data

### ISSUE THREAD

**Issue by Oufattole** [mmcdermott/MEDS_transforms#205]
Patients with no static data are not represented in the `static_df` generated during the [tokenization transform](https://github.com/mmcdermott/MEDS_transforms/blob/main/src/MEDS_transforms/transforms/tokenization.py
).

Expected Behavior:
All patients should have a row in `static_df`, even if they lack static data.

Current Behavior:
When there is no static data in the dataset (for example if you filter out all the static measurements in a prior filter stage), the static data in the schema folder is all empty.

**Comment by Oufattole** [comment]
Oh actually I just had a bug in my code, and I think MIMICIV actually always has GENDER filled in for patients.

**Comment by mmcdermott** [comment]
Related: #197

**Comment by mmcdermott** [comment]
Hmm -- it looks like maybe we just need to push a new version with this change? I see changes in dev from PR #198 that were added to solve #197 that look like they should fix this. @Oufattole does that look right to you?

**Comment by mmcdermott** [comment]
Seems like there was a PR to fix this that didn't go in for some reason: https://github.com/mmcdermott/MEDS_transforms/pull/199

**Comment by mmcdermott** [comment]
@Oufattole I pushed a new version with the hotfix in; please test it and reopen this issue if the problem is not fixed.
