### ISSUE TITLE
Add `extract_numeric_values` transformation

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_transforms#57]
This may leverage the match & revise syntax of #101

**Comment by mmcdermott** [comment]
@prenc is there any setting that you know of where you'd use this transformation other than the blood pressure example we've already discussed in the `split_measurements` transform discussion on #58?

**Comment by prenc** [comment]
> @prenc is there any setting that you know of where you'd use this transformation other than the blood pressure example we've already discussed in the `split_measurements` transform discussion on #58? If not, I will de-prioritize this transformation in the interim, given we can handle that conversion directly in `split_measurements`.

No, I have not used this anywhere else.

**Comment by mmcdermott** [comment]
Great, thanks; then for now I'm going to de-prioritize this and we can come back to it as needed.

**Comment by mmcdermott** [comment]
@prenc it seems like we'd also want this for BMI: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L388C3-L399C10

Is that right?

**Comment by prenc** [comment]
> @prenc it seems like we'd also want this for BMI: https://github.com/ipolharvard/ethos/blob/master/src/ethos/tokenize/mimic/preprocessors.py#L388C3-L399C10
> 
> Is that right?

@mmcdermott Not sure, we don't really extract anything in this case. It's a BMI token converted to quantiles with an additional prefix; BMI//Q2, BMI//Q5. My code is a bit overcomplicated here because I wasn't initially planning on doing it this way.

**Comment by mmcdermott** [comment]
> @mmcdermott Not sure, we don't really extract anything in this case. It's a BMI token converted to quantiles with an additional prefix; BMI//Q2, BMI//Q5. My code is a bit overcomplicated here because I wasn't initially planning on doing it this way.

Hmm. But what about the line that is casting the `text_value` to `Float64`? Is that not extracting a numerical value? I'm just trying to make sure we aren't missing some functionality we'll need in some way shape or form.

**Comment by prenc** [comment]
> > @mmcdermott Not sure, we don't really extract anything in this case. It's a BMI token converted to quantiles with an additional prefix; BMI//Q2, BMI//Q5. My code is a bit overcomplicated here because I wasn't initially planning on doing it this way.
> 
> Hmm. But what about the line that is casting the `text_value` to `Float64`? Is that not extracting a numerical value? I'm just trying to make sure we aren't missing some functionality we'll need in some way shape or form.

@mmcdermott Yes, you are right. In this context, it's actually a very simple value extraction that moves values from the `text_value` column to `numeric_value`  converting the type from String to Float64.
